default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password:
  host: localhost
  port: 5432

development:
  <<: *default
  database: db_shopping_cart

test:
  <<: *default
  database: db_shopping_cart_test

production:
  <<: *default
  database: db_shopping_cart_production
